- hosts: all
  become: true

  tasks:
    - import_role:
        name: 'JoergFiedler.freebsd-jail-host'
    - include_role:
        name: 'JoergFiedler.freebsd-jailed-sshd'
      vars:
        jail_net_ip: '10.1.0.10'
        jail_name: 'sshd'
        sshd_jump_host: true
