dist: trusty
sudo: false
language: python
python: 2.7
install:
- wget https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb
- sudo dpkg -i vagrant_1.9.7_x86_64.deb
- pip install ansible==2.6.1
- pip install netaddr
before_script:
- vagrant plugin install vagrant-aws
- ssh-keygen -y -f ~/.vagrant.d/insecure_private_key > ~/.vagrant.d/insecure_private_key.pub
- ln -s ./ JoergFiedler.freebsd-jailed-sshd
script:
- ansible-galaxy install -p ./ -r .requirements.yml
- vagrant box add JoergFiedler/FreeBSD-11.2 --provider aws
- vagrant up --provider aws
- vagrant ssh -c "sudo iocage list"
after_script:
- vagrant destroy -f
env:
  global:
  - secure: jATebx8mrPU8HQLz2pHBfVEOqilb1Qu3/K0Exuxlb0U7yq2+zPMFecrmIPuyENlSc3X7PhxbwUKJMnVROaq6BywJcbV/kCiGlPmnV7wL42PizePmtmpbeZjGOZXdbhPd2y1ii9+Ejv2myqUE6I3Xa87j2hmvyaJmIgH+dqznMbMlNP1Y7goGbyhs63/w81JE4DAIE68HOlYwRqcaaphO7k0VitpE4KKiJboROS/9CqGXY1HfKOVohgKA203g5p7WIPoEObXrZscsvlD3l7iTKQ9NrehM51dxHp59rmbU9KPzYl8Dg3KOMmBouJZiFvJKRYy31a/vUSDIfSq2wEasts5wi7TIpM1Kr+A60eNMheUOYTmm9VFtcEY8IX/GHrXP45O7Y7QouysgV8Gv2oqywyE7fQIB94rEF0jkvn9SM23u7bhST1982lrNrj2UZHn+npa6jJM+LXyoCz462atYKs/k4L6y7k6DgUVKUH+npa2zZ2gv5FG3TtJc9zAC2bNfnxcxhbkZXJ9uugyGOxFzRkknNTxmY6YYwtqpd107dngrcqFMIyxUITdJExrmDpH94kv57SQVb/oEUGsvHR7MRKOesZSJaYBVO06qLz/mgzxEvV4WLr1EMf6KUDJt6cfg/tpIth3J+l7QbrF4QcBJuSSP68MZ20oU570MoiMToPw=
  - secure: rQsggOnexzmE2TTUivm+v5SN+iobjMvVoH4DzIJ6yCHs1SbkxaDWWB3zrWfAJ0w5V2rkTWbKEO9TcnNfc4fuYlTkH6d0GsKkdf44YfkSXQ5TNmLUAfQIyLAtUBCAx6hHoJTkiPK0ifzOoyIb2WTxSx50eGlgu+k2jsCEhkeLOlE9XrM28p47bydduBEdw+GbxNwr36F3DSo1E3GISmCkF2vbhdMSjlgflqPJtIxOENEE/l/WxTYzEd21Qr4P0P9/BtYh7yssXEas6rFUhTEFmYDZt5AWXLy1tDtEjE7NVGUFWorLHbGj5J6h9vMwX325OuTzDYGB9F7umwhTKF5Ng2cZSiBmKpP/M/SN4oiHlB4TwjoKmvGHIr+2tC9ZjFkktdqIRCje9mRMwIyLduoUI5snmvNSBtlYCMQulgQSEyZymTeCNqB2Lbv5evcxp99r4UnMEuulA6VKkabw65B2mynx8pX5BYx1Nxav/+7obgneVMXWdgFI5B28jDrKFX0EQzPXCHVgfdcIU9y0UalRBC3SCIw7i/IFOr+S6TcK7HQkqknhAJ2lcaGMb81050GuAkEFHcGwEDUv0hbgkABNbFp3SEZ0S0z4NgwH4/5QrJS5+lUlilnQDGcpr06SmzW2r/7ZGUlmZW2o2BvXP5TVTkeuU5j5OerH/T5oHJLySsY=
