---
- name: Create ssh user
  lineinfile:
    dest: '{{ jail_home.stdout }}/etc/master.passwd'
    state: present
    insertafter: EOF
    line: '{{ host_sshd_user }}:*:1001:1001::0:0:Remote (ssh) Management User:/home/{{ host_sshd_user }}:/bin/sh'
  register: user

- name: Update user database
  command: pwd_mkdb -p -d {{ jail_home.stdout }}/etc {{ jail_home.stdout }}/etc/master.passwd
  when: user.changed

- name: Create .ssh directry for ssh user
  file:
    path: '{{ jail_home.stdout }}/home/{{ host_sshd_user }}/.ssh'
    owner: '{{ host_sshd_user }}'
    group: '{{ host_sshd_user }}'
    mode: 0700
    state: directory

- name: Copy authorized keys file
  copy:
    src: '{{ host_sshd_authorized_keys_file }}'
    dest: '{{ jail_home.stdout }}/home/{{ host_sshd_user }}/.ssh/authorized_keys'
    owner: '{{ host_sshd_user }}'
    group: '{{ host_sshd_user }}'

