---
- name: Create ssh user
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '{{ jail_home.stdout }}/etc/master.passwd'
    state: present
    insertafter: EOF
    line: '{{ ssh_user_master_passwd_entry }}'
  notify:
    - Update {{ jail_name }} user database

- name: Create .ssh directry for ssh user
  file:
    path: '{{ jail_home.stdout }}{{ sshd_user_home }}/.ssh'
    owner: '{{ sshd_user_uid }}'
    group: '{{ sshd_user_gid }}'
    mode: 0700
    state: directory

- name: Copy authorized keys file
  copy:
    backup: '{{ jail_backup_old_files }}'
    src: '{{ sshd_authorized_keys_file }}'
    dest: '{{ jail_home.stdout }}{{ sshd_user_home }}/.ssh/authorized_keys'
    owner: '{{ sshd_user_uid }}'
    group: '{{ sshd_user_gid }}'
