---
- name: Reload jail s sshd
  command: |
    /usr/local/bin/iocage exec {{ jail.name }} service sshd reload
  when: not jail_created is changed

- name: Update user database
  command: |
    /usr/local/bin/iocage exec {{ jail_name }} pwd_mkdb -p -d /etc /etc/master.passwd
